### ISSUE TITLE
没有显示我自己的post

### ISSUE THREAD

**Issue by macong0420** [godruoyi/gblog#18]
我将Src/content/posts文件夹里的.md文件都删除了,然后添加了我自己的文件,但是页面没有跟新.还需要从新部署吗?

**Comment by godruoyi** [comment]
hi @macong0420 因为这是一个静态博客，这意味着你修改了任何内容你都需要重新部署才会生效。

你部署的是哪个平台呢，vercel 的话我记得只要你部署成功后下次在提交代码更新时，它会自动帮你在部署一次的。

**Comment by godruoyi** [comment]
先关闭了，如果你又遇到了这个问题，我们再来一起看看。
