### ISSUE TITLE
The Composer mirrors package is no longer available

### ISSUE THREAD

**Issue by reallyli** [godruoyi/gblog#4]
https://github.com/godruoyi/gblog/blob/1dddf9ca57185989a1e3c875ad687185971377e7/composer.lock#L24

- Goto https://developer.aliyun.com/composer

**Comment by godruoyi** [comment]
抱歉，项目提交时用的 Laravel China 的镜像，但现在 Laravel China 已经停用了，你可以直接 remove composer.lock 后重新安装。我以后更新下最新的代码。
