### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yinzhidong** [godruoyi/gblog#8]
![image](https://github.com/godruoyi/gblog/assets/22864444/9ba32d0e-ad9b-4c0e-8510-881b1bc2d97e)

运行`npm run build` 报错如上的错误

使用的分支是 `master`
node版本是 `v18.20`
npm版本是 `10.5.0`

npm run dev可以正常运行

**Comment by godruoyi** [comment]
谢谢你的反馈，让我看看👀

**Comment by godruoyi** [comment]
我在本地测试是可以的， 你要不然试着更新下 node 版本试试呢？
```
node: v20.13.1
npm: 10.5.2
```

ps: 建议你使用 gblog-template 分支，因为默认的 astro 分支(注意默认的分支是 astro)包含了我所有的博客数据，在 build 时可能会很慢因为首次 build 需要优化所有图片。

当然 astro 分支的代码是最新的，如果你嫌 build 太慢可以删除一些 `src/content/posts/` 下的文章试试，目前没有找到 disable image optimization 的选项。

**Comment by yinzhidong** [comment]
> 我在本地测试是可以的， 你要不然试着更新下 node 版本试试呢？
> 
> ```
> node: v20.13.1
> npm: 10.5.2
> ```
> 
> ps: 建议你使用 gblog-template 分支，因为默认的 astro 分支(注意默认的分支是 astro)包含了我所有的博客数据，在 build 时可能会很慢因为首次 build 需要优化所有图片。
> 
> 当然 astro 分支的代码是最新的，如果你嫌 build 太慢可以删除一些 `src/content/posts/` 下的文章试试，目前没有找到 disable image optimization 的选项。

好的，我尝试一下你的版本，🙏

**Comment by godruoyi** [comment]
hi @yinzhidong 最近又遇到什么错误吗？很期待收到你的反馈并且很乐意帮忙一起解决。

**Comment by godruoyi** [comment]
我暂时将这个问题关闭了，你要是还有其他疑问的话欢迎告诉我。
